### ISSUE TITLE
tuningProvider off by 3 semitones?

### ISSUE THREAD

**Issue by dbadb** [free-audio/clap-plugins#21]
The current implementation seems to map key 72 to 440Hz.  According to [SPN](https://en.wikipedia.org/wiki/Scientific_pitch_notation), key 69 should produce 440Hz.  If this is intended to show how we can implement alternate tunings, then perhaps a code-comment is called for?  Otherwise, I think this is a bug.

```cpp
return 440 * tuningToRatio(key - 12 * 6);
```
should be ?

```cpp
return 440 * tuningToRatio(key - 69);
```

**Comment by abique** [comment]
Good catch!
