### ISSUE TITLE
How to clean build files?

### ISSUE THREAD

**Issue by ghost** [free-audio/clap-plugins#8]
All the clap-plugin files are built inside `/usr/local/lib`, but there is no way to "uninstall" or "clean" them. I've tried `sudo cmake --build --preset ninja-system --target clean`, but it is not working fine.

**Comment by abique** [comment]
I'm not aware of a uninstall function.
Usually it isn't an issue as this is done by a package manager.

You could install it again to see the list of files which are installed and then use that to cleanup.
